[package]
name = "xidle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
x11 = { version = "2.19.*", features = ["xlib", "xss"] }
emacs = "0.18.0"

[lib]
crate-type = ["cdylib"]
